name: 🐛 Bug Report
description: Create a report to help us improve PerfLens
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of PerfLens are you running?
      placeholder: e.g., 1.0.0
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where are you running PerfLens?
      options:
        - Development
        - CI/CD
        - Production
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Please share your PerfLens configuration (remove any sensitive data)
      render: javascript
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code.
      render: shell
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.